events { worker_connections 1024; }

http {
    upstream vscode     { server vscode:8080; }
    upstream gitea      { server gitea:3000; }
    upstream mattermost { server mattermost:8065; }

    server {
        listen 80;

        location /code/ {
            proxy_pass http://vscode/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /git/ {
            proxy_pass http://gitea/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /chat/ {
            proxy_pass http://mattermost/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location / {
            return 301 /code/;
        }
    }
}